{% set name = "rucio-clients" %}
{% set version = "35.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bc79602193e271f66c3fdb43e7abda7903026795d6f3c5d71afb5e52250f8d92

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
  run:
    - python >=3.9
    - dogpile.cache ~=1.2.2
    - jsonschema ~=4.23.0
    - requests ~=2.32.3
    - tabulate ~=0.9.0
    - urllib3 ~=1.26.19

test:
  imports:
    - rucio
    - rucio.client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://rucio.cern.ch/
  summary: Rucio Client Lite Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bari12
