{% set name = "rucio-clients" %}
{% set version = "36.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b112ecd8c48d0dec0d7dfc32f6145192461134c5f984e03cf654d999a42161e7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - dogpile.cache >=1.2.2
    - jsonschema >=4.23.0
    - packaging >=24.1
    - requests >=2.32.3
    - rich >=13.7.1
    - tabulate >=0.9.0
    - urllib3 >=1.26.19

test:
  imports:
    - rucio
    - rucio.client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://rucio.cern.ch/
  summary: Rucio Client Lite Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bari12
